# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: dotnet build
      run: dotnet build -c Release

    - name: dotnet test
      run: dotnet test -c Release --no-build --verbosity normal Thousand.Tests

    - name: dotnet publish
      if: matrix.platform == 'windows-latest'
      run: dotnet publish Thousand.Web -c Release --no-build -o "${{env.DOTNET_ROOT}}\thousand"

    - name: Upload artifact for deployment job
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/thousand

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thousandwords'
        # slot-name: 'staging'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5574ab46d63d4e05919351e4aff5b797 }}
        package: .
