name: nuget

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: dotnet build
      run: dotnet build -c Release

    - name: dotnet test
      run: dotnet test -c Release --no-build --verbosity normal Thousand.Tests

    - name: dotnet pack Thousand.Core
      run: dotnet pack -c Release --no-build -p:RepositoryBranch=release -p:RepositoryCommit=${GITHUB_SHA} Thousand.Core -o .

    - name: dotnet pack Thousand.CLI
      run: dotnet pack -c Release --no-build -p:RepositoryBranch=release -p:RepositoryCommit=${GITHUB_SHA} Thousand.CLI -o .

    - name: dotnet pack Thousand.LSP
      run: dotnet pack -c Release --no-build -p:RepositoryBranch=release -p:RepositoryCommit=${GITHUB_SHA} Thousand.LSP -o .

    - name: dotnet nuget push
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
