name: nuget

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  push:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: dotnet build
      run: dotnet build -c Release -p:ContinuousIntegrationBuild=true -p:RepositoryBranch=release -p:RepositoryCommit=$GITHUB_SHA -p:SymbolPackageFormat=snupkg

    - name: dotnet test
      run: dotnet test -c Release --no-build --verbosity normal Thousand.Tests

    - name: dotnet pack Thousand.Core
      run: dotnet pack -c Release --no-build Thousand.Core -o .

    - name: dotnet pack Thousand.CLI
      run: dotnet pack -c Release --no-build Thousand.CLI -o .

    - name: dotnet nuget push
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
